# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
      # Runs a single command using the runners shell
        with:
        java-version: 1.8
      - name: Run a one-line script
        run: echo Hello, world!
        
    test:
        runs-on: ubuntu-latest
        name: Running tests
        needs: compile    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          - name: Run unit tests
          run: mvn test 
    build:
    runs-on: ubuntu-latest
    name: Run mvn build and generate coverage report
    needs: test
        
    steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
                java-version: 1.8
            -name: Build with Maven
            run: mvn -B package --file pom.xml -Dmaven.test.skip=true
          - name: generate report codecov
            run: mvn cobertura:cobertura
          - name: Upload coverage
            if: success()
            run: |
                curl -s https://codecov.io/bash | bash
            env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            shell: bash


#        uses: actions/setup-java@v1
#
#        with:
#
#          java-version: 1.8
#
#      - name: Build with Maven
#
#        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
#
#      - name: generate report codecov
#
#        run: mvn cobertura:cobertura
#
#      - name: Upload coverage
#
#        if: success()
#
#        run: |
#
#          curl -s https://codecov.io/bash | bash
#
#        env:
#
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#
#        shell: bash

      # Runs a set of commands using the runners shell #we do not know are the prase of code important  
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
          
 
